### ISSUE TITLE
Add support for wxWin

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/ttBld#199]
### Description:
**wxWin** is a command line tool for converting a .rc file into source files. To support this in .ninja, we need the following:

```
rule wxWin
  command = wxWin.exe --c $in
  description = Converting $in into source files

drvFile.cpp genFile.cpp ...: wxWin file.rc
```

In .srcfiles.yaml, we need a **wxWin:** section:

```
wxWin:
# Specifies resource files to convert by wxWin, and what their generated filenames will be.
    file1.rc: drvFile1.cpp, genFile1.cpp, drcFile2.cpp, genFile2.cpp
    file2.rc: drvFile1.cpp, genFile1.cpp, drcFile2.cpp, genFile2.cpp
    etc.
```

### Issue Type:
- [ ] Bug report
- [x] Feature request
- [ ] Design change request
- [ ] Other
